version: "3.9"

services:
  database:
    image: postgres:14.4-alpine
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_dompixel
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
    
