version: "3.9"

services:
  database:
    image: postgres:14.4-alpine
    container_name: database_container
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: db_dompixel
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  app:
    build: .
    container_name: node_container
    ports:
      - 5000:5000
    volumes:
      - .:/usr/app
    links: 
      - database
    depends_on: 
      - database

volumes:
  postgres:
    
